In [152]:
import numpy as np
from scipy.linalg import lu


a = np.array([1,1,0])
b = np.array([-1,2,5])
M = np.array([[2,-1,0],
            [-1,2,-1],
            [0,-1,2]])

mat = [[2, -1, 0],
       [-1, 2, -1],
       [0, -1, 2]]


p,l,u = lu(M)
print(l,u)
print('a) inner product between a and b =', np.dot(a,b))
print('b) matrix-vector product between M and b =', np.dot(M,b))
print('c) l2 norm of b =', np.sqrt(np.sum(np.square(b))))

[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]] [[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]
a) inner product between a and b = 1
b) matrix-vector product between M and b = [-4  0  8]
c) l2 norm of b = 5.477225575051661


In [151]:
import numpy as np

def forward_sub(L, b):
    """Given a lower triangular matrix L and right-side vector b,
    compute the solution vector y solving Ly = b."""

    y = []
    for i in range(len(b)):
        y.append(b[i])
        for j in range(i):
            y[i]=y[i]-(L[i, j]*y[j])
        y[i] = y[i]/L[i, i]

    return y

def backward_sub(U, y):
    """Given a lower triangular matrix U and right-side vector y,
    compute the solution vector x solving Ux = y."""

    x = np.zeros_like(y)

    for i in range(len(x), 0, -1):
      x[i-1] = (y[i-1] - np.dot(U[i-1, i:], x[i:])) / U[i-1, i-1]

    return x

def lu_factor(A):


    #LU decompostion using Doolittles method

    L = np.zeros_like(A)
    U = np.zeros_like(A)

    N = np.size(A,0)
    for k in range(N):
        L[k, k] = 1
        U[k, k] = (A[k, k] - np.dot(L[k, :k], U[:k, k])) / L[k, k]
        for j in range(k+1, N):
            U[k, j] = (A[k, j] - np.dot(L[k, :k], U[:k, j])) / L[k, k]
        for i in range(k+1, N):
            L[i, k] = (A[i, k] - np.dot(L[i, :k], U[:k, k])) / U[k, k]

    print(L, U)
    return (L, U)

def lu_solve(L, U, b):
    # Step 1: Solve Uy = b using forward substitution

    # Step 2: Solve Lx = y using backward substitution

    y = forward_sub(L,b)
    x = backward_sub(U,y)

    return x


def linear_solve(A, b):
    # ...

    L, U = lu_factor(A)
    x = lu_solve(L,U,b)
    return x


A = M

print(linear_solve(A,b))

[[1 0 0]
 [0 1 0]
 [0 0 1]] [[ 2 -1  0]
 [ 0  2 -1]
 [ 0  0  2]]
[0.625 2.25  2.5  ]


In [150]:
def luDecomposition(M, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
 
    # Decomposing matrix into Upper
   # and Lower triangular matrix
    
   
    U = []
    for i in range(n):
 
        # Upper Triangular
        for k in range(i, n):
 
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
             
            # Evaluating U(i, k)
            upper[i][k] = M[i][k] - sum

        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
 
                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                # Evaluating L(k, i)
                lower[k][i] = int((M[k][i] - sum) /
                                  upper[i][i])
 
    # setw is for displaying nicely
    print("Lower Triangular\t\tUpper Triangular")
 
    # Displaying the result :
    for i in range(n):
 
        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
 
        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")
    print(np.matmul(lower,upper))
    z = []
    for i in range(len(b)):
        z.append(b[i])
        for j in range(i):
            z[i] = z[i]-(lower[i][j]*z[j])
        z[i] = z[i]/lower[i][i]

    #print(z)





    x = np.zeros_like(z)
    for i in range(len(x), 0, -1):
        x[i-1] = (z[i-1] - np.dot(upper[i-1][i:], x[i:])) / upper[i-1] [i-1]
    print (x)

luDecomposition(M, 3)


Lower Triangular		Upper Triangular
1	0	0		2	-1	0	
0	1	0		0	2	-1	
0	0	1		0	0	2	
[[ 2 -1  0]
 [ 0  2 -1]
 [ 0  0  2]]
[0.625 2.25  2.5  ]


In [90]:
import math
def Cholesky_Decomposition(M, n):
 
    lower = [[0 for x in range(n + 1)]
                for y in range(n + 1)];
 
    # Decomposing a matrix
    # into Lower Triangular
    for i in range(n):
        for j in range(i + 1):
            sum1 = 0;
 
            # summation for diagonals
            if (j == i):
                for k in range(j):
                    sum1 += pow(lower[j][k], 2);
                lower[j][j] = int(math.sqrt(M[j][j] - sum1));
            else:
                 
                # Evaluating L(i, j)
                # using L(j, j)
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k]);
                if(lower[j][j] > 0):
                    lower[i][j] = int((M[i][j] - sum1) /
                                               lower[j][j]);
 
    # Displaying Lower Triangular
    # and its Transpose
    print("Lower Triangular\t\tTranspose");
    for i in range(n):
         
        # Lower Triangular
        for j in range(n):
            print(lower[i][j], end = "\t");
        print("", end = "\t");
         
        # Transpose of
        # Lower Triangular
        for j in range(n):
            print(lower[j][i], end = "\t");
        print("");
 
Cholesky_Decomposition(M, 3);

Lower Triangular		Transpose
1	0	0		1	-1	0	
-1	1	0		0	1	-1	
0	-1	1		0	0	1	
